### PR TITLE
Feature: Add additional models to blacklisted object table.

### PR DESCRIPTION
**Pull request by dp-mods**
Added more props to the blacklisted props

### CODE REVIEW

**Comment by dp-mods** [comment]
Added props such as: Containers, Vehicle Prop Models (Such as crashed helicopter), fences and more to the blacklist.

Should help prevent people raining the apocalypses on servers

**Comment by NotSomething0** [comment]
Thanks for the contribution! 
A few issues before I can merge this, the model name inside the brackets needs to be placed inside backticks instead of quotes as this is much faster then using [GetHashKey](https://runtime.fivem.net/doc/natives/?_0x98EFF6F1) for checking the model hash see ([compile-time Jenkins hashes](https://cookbook.fivem.net/2019/06/23/lua-support-for-compile-time-jenkins-hashes/)). Also if you could indent one tab and set the indices to true rather than the model name that would be a big help. Other than those couple of things this looks.

**Comment by dp-mods** [comment]
Sweet, I'll sort that over the coming days

**Comment by NotSomething0** [comment]
New update removes entity blacklisting in favor of entity whitelisting making this pull request obsolete. Thanks for the contribution though!

**Pull request closed without merging**
